# This file pipline for project Simple Nodejs Weather App with stage build and test

build:
  stage: build
  script:
    - echo "Building..." 
    - npm install
  tags:
    - vmn2      
test:
  stage: test
  script:
    - echo "Testing..."
    - npm run test
  tags:
    - vmn2 

deploy:
  stage: deploy
  script:
    - docker stop
    - docker run -d -p 3000:3000
  tags:
    - vmn2


