# This file pipline for project Simple Nodejs Weather App with stage build and test

build:
  stage: build
  script:
    - echo "Building..." 
    - docker build . -t vmn3/simple-nodejs-weather-app
  tags:
    - vmn2      
    
deploy:
  stage: deploy
  script:
    - docker stop vmn3/simple-nodejs-weather-app
    - docker rm vmn3/simple-nodejs-weather-app
    - docker run -p 3000:3000 -d vmn3/simple-nodejs-weather-app
  tags:
    - vmn2 


