# This file pipline for project Simple Nodejs Weather App with stage build and test

build:
  stage: build
  script:
    - echo "Building..."
    - npm install 
    
  tags:
    - vmn2      
    
test:
  stage: test
  script:
    - echo "Testing..."
    - npm run test
  tags:
    - vmn2  

