# This file pipline for project Simple Nodejs Weather App with stage build and test

build:
  stage: build
  script:
  
    - npm run build
  tags:
    - vmn2      
    
test:
  stage: test
  script:
    
    - npm run test
  tags:
    - vmn2  

