version: '3'
### Author:vmn3

services:  
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks: 
      - private-network

  