version: '3'
### Author:vmn3

services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      #- "443:443"
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks: 
      - private-network
  simple-nodejs-weather-app:
    image: simple-nodejs-weather-app
    container_name: simple-nodejs-weather-app
    build: ./
    depends_on:
      - proxy
    ports:
      - '3000'
    networks:
      - private-network



  